### ISSUE TITLE
error php spark publish dataTables.bootstrap4.min.mjs

### ISSUE THREAD

**Issue by hunter-and1** [tattersoftware/codeigniter4-frontend#31]
when u use 
![image](https://user-images.githubusercontent.com/15271465/216161344-719a681b-647d-46ae-ad0b-89c039a36cec.png)

**Comment by MGatner** [comment]
Publisher doesn't allow MJS files to be placed in **public/**. Read the framework docs on how to modify Publisher's permissions.
